name: Update ipset.json

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 hours after midnight

jobs:
  update_ipset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update ipset.json
        run: python update-ipset.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipset.json
          git commit -m "Update ipset.json $(date) [skip ci]" || echo "No changes to commit"
          git push